### ISSUE TITLE
ROI extraction with custom atlas; module not found error

### ISSUE THREAD

**Issue by macwoodburn** [cohenlabUNC/clpipe#255]
I'm running into a module not found error when running ROI extraction with a custom atlas. 

My command: `fmri_roi_extraction -config_file /proj/cohenlab/projects/MAP/clpipe_config_maptasks_062022.json -atlas_name Schaefer300 -custom_atlas Schaefer2018_300Parcels_7Networks_order_FSLMNI152_1mm.Centroid_XYZ.txt -custom_label Schaefer2018_300Parcels_7Networks_order_FSLMNI152_1mm.Centroid_labels.txt -custom_type sphere -radius 4 -submit`

The error: `Traceback (most recent call last):
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/bin/fmri_roi_extraction", line 11, in <module>
    load_entry_point('clpipe==1.5.0.5', 'console_scripts', 'fmri_roi_extraction')()
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/clpipe/roi_extractor.py", line 5, in <module>
    from nilearn.input_data import NiftiSpheresMasker
  File "/nas/longleaf/home/mawoodbu/.local/lib/python3.6/site-packages/nilearn/input_data/__init__.py", line 5, in <module>
    from .nifti_masker import NiftiMasker
  File "/nas/longleaf/home/mawoodbu/.local/lib/python3.6/site-packages/nilearn/input_data/nifti_masker.py", line 9, in <module>
    from sklearn.externals.joblib import Memory
ModuleNotFoundError: No module named 'sklearn.externals.joblib'`

This error remains when testing out clpipe/1.5.0, and clpipe/1.4.0 via 'module add clpipe'.

**Comment by wasciutto** [comment]
This seems to have been a deployment / installation issue and not a codebase issue - closing for now.
